---
version: "3.8"

services:
  tengine-http:
    image: axizdkr/tengine:3.0.0.
    container_name: tengine-http
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d/:/etc/nginx/conf.d/
    networks:
      - web-in

networks:
  web-in:
    name: web-in
